language: python
cache: pip
python:
  - "3.6"
services:
  - redis-server
  - rabbitmq
  - mongodb
install:
  - pip install -r requirements.txt
  - pip install pycodestyle
script:
  - pytest -vv
  - pycodestyle --show-source --exclude=.env,.tox,dist,docs,build,*.egg .
