language: python
cache: pip
python:
  - "3.6"
services:
  - redis-server
  - rabbitmq
  - mongodb
install:
  - pip install -r requirements.txt
  - pip install pycodestyle
script:
  - pytest -vv
  - pycodestyle --statistics --show-source --exclude=.env,.tox,dist,docs,build,*.egg .
  - xmllint --noout --relaxng xml/process-spec.rng xml/all-inputs.2018-04-04.xml
